spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:h2:file:./database
    driver-class-name: org.h2.Driver
    username: root
    password: root

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  servlet:
    session:
      timeout: 24h
      cookie:
        same-site: strict

springdoc:
  packages-to-scan: com.gamevault.controller

app:
  kafka:
    topics:
      steam-save: steam-save-topic

igdb:
  client:
    id: YOUR-IGDB-CLIENT-ID
    secret: YOUR-IGDB-CLIENT-SECRET

steam:
  api:
    key: YOUR-STEAM-API-KEY

api:
  prefix: /api/v1
